### ISSUE TITLE
Sleep tutorial not running

### ISSUE THREAD

**Issue by aranas** [fieldtrip/website#116]
@robertoostenveld @matsvanes @simonhomoelle 

In the sleep tutorial once the dataset is epoched, something goes wrong with the hdr field, as chantype and chanunit are empty. Therefore subsequent calls to ft_artifact_muscle throw an error:

Index exceeds matrix dimensions.

Error in ft_fetch_header (line 56)
  hdr.chantype = data.hdr.chantype(hdrindx);

Error in ft_artifact_zvalue (line 212)
  hdr = ft_fetch_header(data);

Error in ft_artifact_muscle (line 152)
  [tmpcfg, artifact] = ft_artifact_zvalue(tmpcfg, data);

I could not see Freddy as an active github user, so I am not sure who to assign to this. I have informed him via email about the bug.

**Comment by robertoostenveld** [comment]
I will look at it.

**Comment by robertoostenveld** [comment]
have you already made any edits to the sleep.md file? If so, I can better refrain from making edits myself, as that may result in merge conflicts.

**Comment by aranas** [comment]
no, no edits

**Comment by robertoostenveld** [comment]
I found the error around line 80 in ft_fetch_header. It was due to the renaming of the channels using ft_apply montage, which caused the data.hdr.label and data.label to be different. It should be fixed with https://github.com/fieldtrip/fieldtrip/pull/1074

Can you continue with testing the tutorial?

**Comment by aranas** [comment]
awesome, thanks! will continue testing
