### ISSUE TITLE
oxford tutorial should be in its own directory

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#122]
Hi @Spaak, regarding #121 please do not add (modified) copies of tutorials under /tutorial, but place them under /workshop/xxx where xxx is the event for which it was made. Otherwise the top level tutorials  become too hard to maintain due to the forking of content. Or if you want, consider properly updating/improving the top level tutorial that you are interested in.

**Comment by Spaak** [comment]
Sorry, will file and merge pull request (including other changes like a workshop page) later today. (I merged #121 immediately yesterday because Nadine was waiting for the page to appear on the website.)

I did make some changes to the general figures in the sensor_analysis tutorial, but I think we shouldn't change that one specifically for the Oxford workshop. FYI the fork is a copy of that one, with added bit on preprocessing and the stuff on EMG coherence removed.

**Comment by robertoostenveld** [comment]
@Spaak I think this is now the case, right? If so, please close this issue.
