### ISSUE TITLE
implement a matlab2markdown function

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#14]
This would slightly resemble the code that is now in utilities/ft_documentationreference and which takes the help of a MATLAB function and converts it into Dokuwiki format. 

Just some ideas:

    matlab2dokuwiki(...)
    matlab2markdown(...)
    markdown2matlab(...)

where converting dokuwiki2matlab is not needed (since we will not move in that direction any more). The reason for creating the matlab2dokuwiki function is that it is the current baseline, so would allow testing that overall functionality remains functional.

    function matlab2markdown(infile,outfile, ...)

where optional arguments would come in key-value pairs and could include these (which are both "yes" for the current dokuwiki implementation)

    fieldtripreflink yes/no   link to online fieldtrip reference documentation
    helponly yes/no           only convert the help
    headertext                string
    footertext                string

**Comment by robertoostenveld** [comment]
@dieloz @aranas, my idea would be that you could use it on the example script and convert back/forth between the MATLAB script and the Markdown version for the website. Having it in MATLAB rather than as Linux command line tool ensures it also works on Windows. Note that not all formatting would have a logical mapping between the two. But even with a limited scope, it would be useful.

**Comment by aranas** [comment]
I had a first go at the matlab2markdown & markdown2matlab scripts. For the matlab2dokuwiki I am not entirely clear on how it will be used, so maybe we could discuss this before continuing. Right now the two functions simply enable one to convert between the two filetypes without loosing any markdown syntax but also being able to transform from markdown to matlab such that it can be run in the editor. 
Before I create a pull request, I had a question.

Where exactly should I place the functions? I would have put them in the website repo, but since the ft_documentationreference function was located in the Fieldtrip software repo, I am unsure.

**Comment by robertoostenveld** [comment]
Sounds good! I think they should go in fieldtrip/utilities, since we would want to call them from the MATLAB command line and from ft_documentationreference. As such, I started this issue at the wrong spot.

**Comment by robertoostenveld** [comment]
These have been implemented. Furthermore, I updated the ft_documentationreference and ft_documentationindex functions.
