### ISSUE TITLE
indicate language in comment section

### ISSUE THREAD

**Issue by jcolomb** [fieldtrip/website#176]
For newbies like me, "scripts" is not very informative, is it python code, linux stuff or can it be used on windows bash,... would be nice to specify

**Comment by robertoostenveld** [comment]
Please suggest a concrete proposal to update the documentation. Which text would you like to appear where?

**Comment by jcolomb** [comment]
sorry, I was referring to http://www.fieldtriptoolbox.org/workshop/madrid2019/bids_sedation/
what type of script is it?

**Comment by robertoostenveld** [comment]
That is a MATLAB script. 

Since FieldTrip is a MATLAB toolbox, I think it is obvious to most people that most scripts on the website are MATLAB. Only where it is not MATLAB (there are some Python and BASH sections), it is explicitly indicated.

I can imagine that when landing on that page after a google search, it can be confusing. Please check getting started (first link in the menu), which I just made a little bit more explicit.

**Comment by robertoostenveld** [comment]
I just checked your ORCID profile and see that you are into open data management and FAIR. Perhaps I can use this opportunity to broaden the discussion.

On http://www.fieldtriptoolbox.org/example/bids/ you can find more examples of BIDS, using FieldTrip and MATLAB as tools to organize and annotate raw (source) data. The last week I have been busy on making more examples, and extending the [data2bids](https://github.com/fieldtrip/fieldtrip/blob/master/data2bids.m) function to deal with more data. This is the type of data that at the [Donders Institute ](https://www.ru.nl/donders/) we often record along with fMRI, EMG and EEG. 

Please see https://docs.google.com/document/d/1_E0BS9F3AIK86swmhNWWcjhhT6SJ2zfZKOZ0E965ZA0/edit?usp=sharing for a draft of the examples and feel free to comment. It is still outside of github to facilitate commenting for my less technically skilled colleagues.
