### ISSUE TITLE
false alarm rate is not controlled

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#195]
While preparing work on #192, and along the way resolving #193, I found out that the number of channels showing an effect in the grandavg FIC-FC contrast seems to be larger than it used to be ...

For example, if you compare the figure just below http://www.fieldtriptoolbox.org/tutorial/eventrelatedstatistics/#permutation-test-based-on-t-statistics with the equivalent one from http://old.fieldtriptoolbox.org/tutorial/eventrelatedstatistics#non-parametric_statistics, you can see that the new figure has more channels with an asterix. 

Trying to dig a little bit further into this, I ran the following code to test
```
nchan = 100;
ntime = 100;
nsubj = 10; % it fails for 10, it works for 20

grandavg = [];
grandavg.label = cellstr(num2str((1:nchan)'));
grandavg.time = 1:ntime;
grandavg.avg = randn(2*nsubj, nchan, ntime);
grandavg.dimord = 'subj_chan_time';

%%

cfg = [];
cfg.parameter = 'avg';
cfg.statistic = 'ft_statfun_indepsamplesT';
cfg.alpha = 0.05;
cfg.correctm = 'no';
cfg.correcttail = 'prob';
cfg.tail = 0;
cfg.numrandomization = 1000;

cfg.design(1,1:2*nsubj) = [ones(1,nsubj) 2*ones(1,nsubj)];
cfg.ivar = 1; % the 1st row in cfg.design contains the independent variable

cfg.method = 'montecarlo';
montecarlo = ft_timelockstatistics(cfg, grandavg);

cfg.method = 'analytic';
analytic = ft_timelockstatistics(cfg, grandavg);

% the false alarm rate should be 5%

assert(mean(montecarlo.mask(:))>0.04);
assert(mean(montecarlo.mask(:))<0.06);

assert(mean(analytic.mask(:))>0.04);
assert(mean(analytic.mask(:))<0.06);

%%

cfg.statistic = 'ft_statfun_depsamplesT';
cfg.design(2,1:2*nsubj) = [1:nsubj 1:nsubj];
cfg.uvar = 2; % the 2nd row in cfg.design contains the subject number

cfg.method = 'montecarlo';
montecarlo = ft_timelockstatistics(cfg, grandavg);

cfg.method = 'analytic';
analytic = ft_timelockstatistics(cfg, grandavg);

% the false alarm rate should be 5%

assert(mean(montecarlo.mask(:))>0.04);
assert(mean(montecarlo.mask(:))<0.06);

assert(mean(analytic.mask(:))>0.04);
assert(mean(analytic.mask(:))<0.06);
```

With 10 subjects (as in the example, but also in the other cluster stats tutorials) it does not control the false alarm rate.  With 20 subjects it does.

I think that right now is relevant for @hadrianswall, @Spaak and @schoffelen to be aware of this. We should follow this up!

**Comment by robertoostenveld** [comment]
One improvement to the test code above is to use 
```
cfg.numrandomization = 'all';
```
for the paired test. It can only create N^2 = 1024 (for 10 subjects) unique permutations, and with 1000 permutations there will be many doubles (and not all 1024 unique ones), causing a suboptimal randomization distribution. This should be checked in the tutorials. 

We should consider giving a warning if the number of unique permutations is much smaller than the desired number (I observed in one run 640 unique permutations, where I had asked for 1000).

However, this is not the cause of the issue.

**Comment by hadrianswall** [comment]
I'm sorry for the delay. I was temporarily unreachable via Github.

I have studied the problem, but I cannot reproduce it. (I used 10 subjects in my simulations.)

I added a bit of code to make the evaluation of the FA rate control easier. Specifically, I calculated the empirical FA rate (both for the permutation/Monte-Carlo and the parametric/analytic test) as well their so-called Monte Carlo standard errors. (Here, "Monte Carlo" refers to the fact that you have performed 100*100=10000 statistically independent tests.)

```
% calculate the empirical FA rate and its Monte Carlo confidence interval
empFArateMC=mean(montecarlo.mask(:))
empFArateAn=mean(analytic.mask(:))

empFArateMCSE=sqrt(empFArateMC*(1-empFArateMC)/(nchan*ntime));
empFArateMCCI=[empFArateMC-1.96*empFArateMCSE,empFArateMC+1.96*empFArateMCSE]
empFArateAnSE=sqrt(empFArateAn*(1-empFArateAn)/(nchan*ntime));
empFArateAnCI=[empFArateAn-1.96*empFArateAnSE,empFArateAn+1.96*empFArateAnSE]
```
The Monte Carlo confidence intervals for both the permutation and the parametric statistical test almost always contain the nominal FA rate 0.05. According to theory, they must contain it in 95% of the cases.

I also did a simulation with 1000*1000 channel-time pairs, and the Monte Carlo confidence interval was [0.0495,0.0505].

I did simulations with one-tailed and two-tailed tests, but the latter only with the option cfg.correcttail=alpha. You have used cfg.correcttail=prob, which I never use because I cannot get my head around what multiplying p-values actually means in a permutation framework. I'm not saying that this is the cause of the fact that you found the FA rate not to be controlled. I just don't know what to expect with cfg.correcttail=prob.

**Comment by robertoostenveld** [comment]
I also cannot reproduce it any more, both now return the expected FA rate.

```
>> mean(montecarlo.mask(:))
ans =
    0.0489
>> mean(analytic.mask(:))
ans =
    0.0490
```

Don't know what went wrong when I tried it in December, but I suspect that somewhere in https://github.com/fieldtrip/fieldtrip/pull/1285 there is something wrong (since that is the version of the code I used in testing this).

**Comment by robertoostenveld** [comment]
I found the bug in the changes here
https://github.com/fieldtrip/fieldtrip/pull/1285/files

In cleaning up the code, I accidentally messed up ivar and over:

```
cfg.ivar           = ft_getopt(cfg, 'ivar', 1);
cfg.uvar           = ft_getopt(cfg, 'ivar', 2); % WRONG
```

**Comment by robertoostenveld** [comment]
Please note that this bug was never released, it was only in my own development version.
