### ISSUE TITLE
YouTube embeddings not working "due to cookie settings"

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/website#267]
See title, and e.g. here: http://www.fieldtriptoolbox.org/tutorial/introduction/, where we see "External content is disabled due to cookie settings."

**Comment by robertoostenveld** [comment]
yes, that is the new "feature", not a bug. If you don't allow extenal cookies, we cannot display inline youtube video (since those would set cookies). See #168. 

On http://www.fieldtriptoolbox.org/privacy/ is a button to reset the cookie permission. 

If you feel like it, this is something we can discuss in person. I'll send you a zoom link in Mattermost.

**Comment by Spaak** [comment]
OK, I think I simply never got the popup asking me to approve cookies, due to a "cookie popup" blocker extension I have running. In general I agree this is a good way to handle cookies and external content. I'll polish the functionality a little bit (will file PR).

**Comment by robertoostenveld** [comment]
That makes sense: as long as permission has not been granted by the user (i.e. while the "cookie popup" is shown, or hidden in your case), it is treated as if the permission were declined.
