### ISSUE TITLE
FieldTrip website should have an SSL certificate; maybe switch hosting?

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/website#270]
It has nowadays become standard for all serious websites to be served via https, rather than plain (unsecured) http. https websites are typically also ranked higher in search results (by e.g. Google) than http, and many browsers will now display an explicit "Unsecure" warning when browsing non-secure websites. This trend will likely continue, and it's not unlikely that in a few years time plain http websites will be blocked altogether. It would be appropriate for the FieldTrip website to also be served via https.

Free SSL certificates are available from https://letsencrypt.org/ .

Related to this: the website's hosting is not very stable, with some occasional downtime. I have a rather large and fast hosting package (Vimexx "Compleet", https://www.vimexx.nl/webhosting) which would be more than sufficient to also host the FieldTrip website. I expect to keep this hosting, or similar, during my lifetime. I'd be happy to host the website from there (at no charge). An additional advantage would be the very easy addition of an SSL certificate, with no server configuration required. We could have the jekyll build run on wherever it's running now (your Raspberry Pi?) and sync the website files to my hosting via SSH/FTP. What do you think @robertoostenveld?

**Comment by robertoostenveld** [comment]
Hi Eelke, this addresses two topics, which I understand perhaps might be addressed in one go.

- the SSL certificate -> yes, I agree
- switching hosting -> hmm ... (see below)

I hardly ever get complaints about the website being down. That was more often with the previous dokuwiki site, which from time to time also had other issues (spam, hacking). Right now I think that you are specifically sensitive to the website downtime because you are running some uptime/downtime detector and get a warning at every incident (which btw I think is usually related to RU networking rather than DCCN issues).

There are costs and risks in switching from institutional hosting to personal (at a company or in someone's basement) hosting.  It is especially the long-term risk that I worry about. The DCCN webserver is in that respect very predictable. To mitigate the risk, being able to fall back to the DCCN webserver would be an option. "Falling back" here to me means something like doing a redirect or a change to the DNS, not setting up (costly wrt time) another server. 

That also means that we could split this in two: first improve the DCCN hosting by adding SSL. Once that is in place, we can do step two and start hosting a copy (for which the html can continue to be rendered on the DCCN webserver) on another external server. At that moment a DNS update is sufficient to switch between the two. 

how do you think about this?

**Comment by Spaak** [comment]
> I hardly ever get complaints about the website being down. That was more often with the previous dokuwiki site, which from time to time also had other issues (spam, hacking). Right now I think that you are specifically sensitive to the website downtime because you are running some uptime/downtime detector and get a warning at every incident

Yes, that's true. Although I can't imagine that during a downtime of ~5 minutes or so during the daytime no one will have tried to access the website. No complaints does not mean no effects, of course. (I.e. people will have been refreshing and it's back after a few minutes--no cause for complaining, just mild annoyance.) The good news is that there hasn't been downtime since December 2019. My impression that the hosting was unstable was mainly due to its performance over the course of 2019:

![image](https://user-images.githubusercontent.com/3042751/92211516-de453400-ee90-11ea-872b-186b186dced2.png)

and it seems like by now the stability has improved a lot. (Uptime robot is still running.)

> (which btw I think is usually related to RU networking rather than DCCN issues).

Very possibly, though also these would be solved by having an external host located at an internet exchange.

> That also means that we could split this in two: first improve the DCCN hosting by adding SSL. Once that is in place, we can do step two and start hosting a copy (for which the html can continue to be rendered on the DCCN webserver) on another external server. At that moment a DNS update is sufficient to switch between the two.
> 
> how do you think about this?

Fully agreed. Also on having the backup with easy switching back through DNS only--imagine I get killed in traffic and no one knows my Vimexx login, or something like that.

I highly recommend Let's Encrypt, although I've only used it to obtain and install certificates through automated web hosting control panels. Their website suggests that installation on a web host to which you have shell access is also trivial: https://letsencrypt.org/getting-started/ points towards Certbot by the Electronic Frontier Foundations https://certbot.eff.org/ which indeed seems very convenient. While I can login on the DCCN webserver (at least I was able to at some point), I can't `sudo`, so you'll have to do this.

**Comment by robertoostenveld** [comment]
I am using letsencrypt on the raspberry pi that I have in my basement as server, but that is with nginx rather than with apache. I am mainly using nginx as the reverse proxy for some internal servers  (i.e. in-house I have some servers with plain http, and nginx slaps the SSL on top of it, so that externally it is https). That letsencrypt configuration was rather complex. Well, I followed a recipe and the end-result was fine, but I cannot say I really understand it. It also involves a cron job for automatic updating. 

I think this is better to leave this to Rene or Ed, who probably are also dealing with this for some other DCCN hosted websites. Can you contact them by email, and CC me on it?

**Comment by robertoostenveld** [comment]
https://www.fieldtriptoolbox.org is now working, and calls to http automatically redirects to the https version. 

We should go through the Jekyll configs to ensure that all links are directly to the https address.

**Comment by Spaak** [comment]
I did a global search/replace, see https://github.com/fieldtrip/website/pull/304 . I'll leave the merge to you, just in case.

**Comment by robertoostenveld** [comment]
It looks good now in the online version, all relative links go to https. 
Thanks for working on this!
