### ISSUE TITLE
create new EEG networking tutorial

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#285]
See https://github.com/fieldtrip/website/compare/143d2caca466...d704d3d5aba1

@schoffelen could you clarify what the plan is, why this is not in a branch during development, and could you also tag Tzvetan on this issue (I could not find him on GitHub)

**Comment by schoffelen** [comment]
Tzvetan is going to contribute a new tutorial, and he does not seem to be on github. In order for him to edit the page through the web-interface, it needs to exist in a way so that he can 'see' it. He promised to work on it tomorrow. 
For now, I will empty the page, and add an 'under construction' statement.

**Comment by robertoostenveld** [comment]
cool! Go-go Tzvetan!
https://www.youtube.com/watch?v=QOwCUkqjzKo

**Comment by schoffelen** [comment]
OK, I added a 'danger' box, rather than emptying the page altogether, so that Tz. has a scaffold structure to use
