### ISSUE TITLE
Make an example that shows how to use simulations to estimate the sample size for a cluster-based permutation test

### ISSUE THREAD

**Issue by wycalan** [fieldtrip/website#364]
Nowadays, providing justification for sample size is required for reporting a research. Many researchers use G*power to conduct a power analysis to estimate the sample size required for their studies. However, this prevailing software is not suitable for EEG research using the cluster-based permutation test to estimate the statistical significance of an effect, because of the non-parametric nature of the test. Here, we provide a method of using simulations to estimate the sample size for cluster-based permutation test.

**Comment by robertoostenveld** [comment]
This is related to https://osf.io/rmqhc/, but also https://www.fieldtriptoolbox.org/example/effectsize/ and to issue #197.

**Comment by robertoostenveld** [comment]
@wycalan I propose that you make an example page `example/effectsize.md` and on that page describe in a few sentences of text, but mainly with a few blocks of MATLAB code, how people can use your code.  

There are a few aspects in the page formatting that are a bit tricky. See https://www.fieldtriptoolbox.org/development/guideline/website. To get started, I recommend that you copy and paste the header from another example md file. 

If you want to include figures I propose that I will create them on my computer (also to check that the example code runs) and I will add them for you. Otherwise: the figures go into `assets` and the way to include them in the page itself is explained [here](https://www.fieldtriptoolbox.org/development/guideline/website/#images).

**Comment by robertoostenveld** [comment]
You should take steps 1-7 from the [tutorial](https://www.fieldtriptoolbox.org/development/git/#tutorial) to create a pull request. Let us know if anything is unclear.

**Comment by wycalan** [comment]
OK, I will work on it next week.

**Comment by wycalan** [comment]
> You should take steps 1-7 from the [tutorial](https://www.fieldtriptoolbox.org/development/git/#tutorial) to create a pull request. Let us know if anything is unclear.

Hi, Robert, I have written a example page and pulled request, see [sample size #368](https://github.com/fieldtrip/website/pull/368)
